// <auto-generated />
using System;
using FormManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911130528_AddUserProfileJsonMetadata")]
    partial class AddUserProfileJsonMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormManagementSystem.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("FormManagementSystem.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FormManagementSystem.Models.RegistrationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("FormManagementSystem.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FormManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FormManagementSystem.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("FormManagementSystem.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("FormManagementSystem.Models.PasswordResetToken", b =>
                {
                    b.HasOne("FormManagementSystem.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormManagementSystem.Models.RefreshToken", b =>
                {
                    b.HasOne("FormManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormManagementSystem.Models.UserProfile", b =>
                {
                    b.HasOne("FormManagementSystem.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("FormManagementSystem.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FormManagementSystem.Models.ProfileMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("UserProfileId");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1
                                .ToJson("Metadata")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");

                            b1.OwnsMany("FormManagementSystem.Models.CertificationMetadata", "Certifications", b2 =>
                                {
                                    b2.Property<int>("ProfileMetadataUserProfileId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("CredentialId");

                                    b2.Property<string>("CredentialUrl");

                                    b2.Property<string>("Description");

                                    b2.Property<bool>("DoesNotExpire");

                                    b2.Property<DateOnly?>("ExpirationDate");

                                    b2.Property<string>("Id");

                                    b2.Property<DateOnly>("IssueDate");

                                    b2.Property<string>("IssuingOrganization")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("ProfileMetadataUserProfileId", "__synthesizedOrdinal");

                                    b2.ToTable("UserProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("ProfileMetadataUserProfileId");
                                });

                            b1.OwnsMany("FormManagementSystem.Models.EducationMetadata", "Education", b2 =>
                                {
                                    b2.Property<int>("ProfileMetadataUserProfileId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<decimal?>("CGPA")
                                        .HasPrecision(4, 2);

                                    b2.Property<string>("Degree")
                                        .IsRequired();

                                    b2.Property<string>("Description");

                                    b2.Property<DateOnly?>("EndDate");

                                    b2.Property<string>("FieldOfStudy")
                                        .IsRequired();

                                    b2.Property<string>("GradeType")
                                        .IsRequired();

                                    b2.Property<string>("Id");

                                    b2.Property<string>("InstitutionLocation")
                                        .IsRequired();

                                    b2.Property<string>("InstitutionName")
                                        .IsRequired();

                                    b2.Property<bool>("IsCurrentlyStudying");

                                    b2.Property<decimal?>("Percentage")
                                        .HasPrecision(5, 2);

                                    b2.Property<DateOnly>("StartDate");

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.HasKey("ProfileMetadataUserProfileId", "__synthesizedOrdinal");

                                    b2.ToTable("UserProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("ProfileMetadataUserProfileId");
                                });

                            b1.OwnsMany("FormManagementSystem.Models.ExperienceMetadata", "Experience", b2 =>
                                {
                                    b2.Property<int>("ProfileMetadataUserProfileId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("CompanyName")
                                        .IsRequired();

                                    b2.Property<string>("Description");

                                    b2.Property<string>("EmploymentType")
                                        .IsRequired();

                                    b2.Property<DateOnly?>("EndDate");

                                    b2.Property<string>("Id");

                                    b2.Property<bool>("IsCurrent");

                                    b2.Property<string>("JobTitle")
                                        .IsRequired();

                                    b2.Property<string>("Location")
                                        .IsRequired();

                                    b2.Property<DateOnly>("StartDate");

                                    b2.HasKey("ProfileMetadataUserProfileId", "__synthesizedOrdinal");

                                    b2.ToTable("UserProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("ProfileMetadataUserProfileId");
                                });

                            b1.Navigation("Certifications");

                            b1.Navigation("Education");

                            b1.Navigation("Experience");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormManagementSystem.Models.UserRole", b =>
                {
                    b.HasOne("FormManagementSystem.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormManagementSystem.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormManagementSystem.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FormManagementSystem.Models.User", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
